### PR TITLE
Publish: Added note about the plugins website's deprecation

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes https://github.com/jquery/jquery.com/issues/134

### CODE REVIEW

**Comment by jzaefferer** [comment]
👍

**Comment by mgol** [comment]
Wouldn't it be better to put the note at the top, before the "Publishing your plugin on the site is a three step process" line?

**Comment by jzaefferer** [comment]
You're right, that should be the first thing.

**Comment by AurelioDeRosa** [comment]
PR updated.

**Comment by mgol** [comment]
LGTM

**Comment by mgol** [comment]
I wanted to land it but apparently I don't have the rights to this repo... Could someone grant me those?

**Pull request merged**
